api_platform:
    title: "MarketReminder"
    graphql:
        enabled: true
        graphiql:
            enabled: true
    http_cache:
        etag: true
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform']
