api_platform:
    title: "MarketReminder - API"
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform']
    http_cache:
        etag: true
        invalidation:
            enabled: true
