framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    session:
        handler_id: ~
    csrf_protection:
        enabled: true
    validation:
        enabled: true
    php_errors:
        log: true
    cache:
        # Redis
        app: 'cache.adapter.redis'
        default_redis_provider: "%env(REDIS_URL)%"

sensio_framework_extra:
    psr_message:
        enabled: false
    router:
        annotations: false
