framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #http_method_override: true
    #trusted_hosts: ~
    session:
        handler_id: ~
    #esi: ~
    #fragments: ~
    csrf_protection:
        enabled: true
    validation:
        enabled: true
    php_errors:
        log: true
    cache:
        # Redis
        app: cache.adapter.redis
        default_redis_provider: "%env(REDIS_URL)%"
