security:
    encoders:
        App\Domain\Models\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: App\Domain\Models\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: db_provider
            logout_on_user_change: true
            form_login:
                login_path: web_login
                check_path: web_login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout
                target: index
            json_login:
                check_path: api_login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
