security:
    encoders:
        App\Domain\Models\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: App\Domain\Models\User
                property: username

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: web_login
                check_path: web_login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout
                target: index
