security:
    encoders:
        App\Interactor\UserInteractor:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: App\Interactor\UserInteractor
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: db_provider
            logout_on_user_change: true
            form_login:
                login_path: web_login
                check_path: web_login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout
                target: index
