security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Interactor\UserInteractor:
            encoder: bcrypt

    providers:
        entity_provider:
            entity:
                class: App\Interactor\UserInteractor
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: entity_provider
            form_login:
                login_path: web_login
                check_path: web_login
                csrf_token_generator: security.csrf.token_manager
