services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #Templating\Extensions\ArrayExtension: ~
    #Templating\Extensions\DateExtension: ~
    #Templating\Extensions\IntlExtension: ~
    #Templating\Extensions\TextExtension: ~
