tests:
    "Pages should load instantly":
        path: "/.*"
        assertions:
            - "main.wall_time < 45ms"
    "Memory should be under control":
        path: "/.*"
        assertions:
            - "main.peak_memory < 5mb"
    "IO wait time should be minimal":
        path: "/.*"
        assertions:
            - "main.io < 15ms"
    "Network in should be minimal":
        path: "/.*"
        assertions:
            - "main.network_in < 400kb"
    '"session.use_strict_mode" should be enabled':
        path:
            - '/.*'
        methods:
            - ANY
        command: '.*'
        assertions:
            - { label: null, expression: 'runtime.configuration.session_use_strict_mode === true' }
        exclude: {  }
    '"expose_php" should be disabled':
        path:
            - '/.*'
        methods:
            - ANY
        command: '.*'
        assertions:
            - { label: null, expression: 'not is_configuration_enabled("expose_php")' }
        exclude: {  }
    '"max_input_time" should be less than 60 seconds on Web requests':
        path:
            - '/.*'
        methods:
            - ANY
        assertions:
            - { label: null, expression: 'runtime.configuration.max_input_time >= 0 and runtime.configuration.max_input_time <= 60' }
        exclude: {  }
    'The realpath cache ttl should be more than one hour in production':
        path:
            - '/.*'
        methods:
            - ANY
        command: '.*'
        assertions:
            - { label: null, expression: 'runtime.configuration.realpath_cache_ttl >= 3600' }
        exclude: {  }
    'A Redis connection should be opened only when queries are made':
        path:
            - '/.*'
        methods:
            - ANY
        command: '.*'
        assertions:
            - { label: null, expression: 'metrics.redis.queries.count > 0' }
        when: 'metrics.redis.connections.count > 0'
        exclude: {  }
    'Only one Redis connection should be used':
        path:
            - '/.*'
        methods:
            - ANY
        assertions:
            - { label: null, expression: 'metrics.redis.connections.count <= 1' }
        exclude: {  }
    'OPcache interned strings buffer should not use more than 85% of its allocated memory':
        path:
            - '/.*'
        methods:
            - ANY
        command: '.*'
        assertions:
            - { label: null, expression: '(runtime.opcache.status.interned_strings_usage.used_memory / runtime.opcache.status.interned_strings_usage.buffer_size) <= 0.85' }
        exclude: {  }
