stages:
    - quality
    - frontend
    - unit
    - functional
    - deployment

insight:
    stage: quality
    image: php:fpm-alpine
    before_script:
        - curl -o insight.phar -s http://get.insight.sensiolabs.com/insight.phar
    script:
        - php insight.phar analyze --no-interaction --no-ansi $INSIGHT_PROJECT_UUID --reference=$CI_COMMIT_SHA --user-uuid=$INSIGHT_USER_UUID --api-token=$INSIGHT_USER_API_KEY --fail-condition="counts.critical > 0"
    allow_failure: true

deptrac:
    stage: quality
    image: php:fpm-alpine
    before_script:
        - curl -LS http://get.sensiolabs.de/deptrac.phar -o deptrac.phar
        - chmod +x deptrac.phar
        - mv ./deptrac.phar /usr/bin/deptrac
    script:
        - deptrac

#encore:
#    stage: frontend
#    image: node:alpine
#    before_script:
#        - yarn install
#    script:
#        - ./node_modules/.bin/encore production
#    cache:
#        paths:
#            - node_modules/
#            - public/build/

phpunit:
    stage: unit
    image: php:fpm-alpine
    services:
        - redis
    before_script:
        - set -xe \
              && apk add --no-cache --virtual .build-deps \
                  $PHPIZE_DEPS \
                  icu-dev \
                  postgresql-dev \
                  zlib-dev \
                  gnupg \
                  graphviz \
                  make \
                  autoconf \
                  git \
                  zip \
                  unzip \
              && docker-php-ext-install \
                  intl \
                  pdo_pgsql \
                  zip \
              && pecl install apcu \
                  && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
                  && docker-php-ext-install pdo_mysql opcache json pdo_pgsql pgsql mysqli \
                  && docker-php-ext-enable apcu mysqli zip \
              && runDeps="$( \
                  scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
                   | tr ',' '\n' \
                   | sort -u \
                   | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
              )" \
              && apk add --no-cache --virtual .php-phpexts-rundeps $runDeps \
              && apk del .build-deps
        - cp docker/php/conf/production/php.ini /usr/local/etc/php/php.ini
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php composer-setup.php
        - php -r "unlink('composer-setup.php');"
        - echo $GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE > $CI_PROJECT_DIR/tests/_credentials/credentials.json
        - echo $GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE > $CI_PROJECT_DIR/config/credentials/google/credentials.json
        - echo $GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE > $CI_PROJECT_DIR/features/assets/_credentials/credentials.json
    script:
        - php composer.phar install -n -a -o
        - php composer.phar dump-autoload -a -o

behat_core:
    stage: functional
    image: php:fpm-alpine
    services:
        - redis
    before_script:
        - set -xe \
              && apk add --no-cache --virtual .build-deps \
                  $PHPIZE_DEPS \
                  icu-dev \
                  postgresql-dev \
                  zlib-dev \
                  gnupg \
                  graphviz \
                  make \
                  autoconf \
                  git \
                  zip \
                  unzip \
              && docker-php-ext-install \
                  intl \
                  pdo_pgsql \
                  zip \
              && pecl install apcu \
                  && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
                  && docker-php-ext-install pdo_mysql opcache json pdo_pgsql pgsql mysqli \
                  && docker-php-ext-enable apcu mysqli zip \
              && runDeps="$( \
                  scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
                   | tr ',' '\n' \
                   | sort -u \
                   | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
              )" \
              && apk add --no-cache --virtual .php-phpexts-rundeps $runDeps \
              && apk del .build-deps
        - cp docker/php/conf/production/php.ini /usr/local/etc/php/php.ini
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php composer-setup.php
        - php -r "unlink('composer-setup.php');"
        - echo $GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE > $CI_PROJECT_DIR/tests/_credentials/credentials.json
        - echo $GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE > $CI_PROJECT_DIR/config/credentials/google/credentials.json
        - echo $GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE > $CI_PROJECT_DIR/features/assets/_credentials/credentials.json
    script:
        - php composer.phar install -n -a -o
        - php composer.phar dump-autoload -a -o

behat_e2e:
    stage: functional
    image: php:fpm-alpine
    services:
        - redis
    before_script:
        - set -xe \
              && apk add --no-cache --virtual .build-deps \
                  $PHPIZE_DEPS \
                  icu-dev \
                  postgresql-dev \
                  zlib-dev \
                  gnupg \
                  graphviz \
                  make \
                  autoconf \
                  git \
                  zip \
                  unzip \
              && docker-php-ext-install \
                  intl \
                  pdo_pgsql \
                  zip \
              && pecl install apcu \
                  && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
                  && docker-php-ext-install pdo_mysql opcache json pdo_pgsql pgsql mysqli \
                  && docker-php-ext-enable apcu mysqli zip \
              && runDeps="$( \
                  scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
                   | tr ',' '\n' \
                   | sort -u \
                   | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
              )" \
              && apk add --no-cache --virtual .php-phpexts-rundeps $runDeps \
              && apk del .build-deps
        - cp docker/php/conf/production/php.ini /usr/local/etc/php/php.ini
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php composer-setup.php
        - php -r "unlink('composer-setup.php');"
        - echo $GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE > $CI_PROJECT_DIR/tests/_credentials/credentials.json
        - echo $GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE > $CI_PROJECT_DIR/config/credentials/google/credentials.json
        - echo $GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE > $CI_PROJECT_DIR/features/assets/_credentials/credentials.json
    script:
        - php composer.phar install -n -a -o
        - php composer.phar dump-autoload -a -o
