stages:
    - frontend
    - unit_tests
    - functional_tests
    - deployment

encore:
    stage: frontend
    image: node:alpine
    before_script:
        - yarn install
    script:
        - ./node_modules/.bin/encore production
    cache:
        paths:
            - node_modules/
            - public/build/
