language: php
php:
    - '7.1'
    - '7.2'
services:
    - docker
before_install:
    - docker pull redis
    - docker pull node
    - docker run -d -p 127.0.0.1:6379:6379 redis
    - docker ps -a
before_script:
    - composer install
    - cp .env.dist .env
    - cp .env.behat.dist .env.behat
script:
    - ./bin/console d:d:c --env=test
    - ./bin/console d:s:c --env=test
    - vendor/bin/phpspec run
    - vendor/bin/phpunit -v
    - vendor/bin/behat --profile default

notifications:
    email: false
