image: php:fpm-alpine

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - set -xe \
              && apk add --no-cache --virtual .build-deps \
              	$PHPIZE_DEPS \
              	icu-dev \
              	postgresql-dev \
              	zlib-dev \
              	graphviz \
              && docker-php-ext-install \
              	intl \
              	pdo_pgsql \
              	zip \
              && pecl install \
              	apcu \
              && docker-php-ext-enable apcu opcache \
              && runDeps="$( \
              	scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
              		| tr ',' '\n' \
              		| sort -u \
              		| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
              )" \
              && apk add --no-cache --virtual .php-phpexts-rundeps $runDeps \
              && apk del .build-deps
          - cp docker/php/conf/production/php.ini /usr/local/etc/php/php.ini
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install -a -o
          - vendor/bin/phpspec run