version: 2
jobs:
    encore:
        docker:
            - image: circleci/node:9.9.0-stretch-browsers
        steps:
            - checkout
            - setup_remote_docker
            - run: sudo yarn install
            name: Restore Yarn Package Cache
                keys:
                    - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
                    - yarn-packages-{{ .Branch }}
                    - yarn-packages-master
                    - yarn-packages-
            - run:
                name: Install Dependencies
                command: yarn install
            - save_cache:
                name: Save Yarn Package Cache
                key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
                paths:
                    - node_modules/
    phpunit:
        docker:
            - image: circleci/php:7.2.2-apache-node-browsers
            - image: redis
        steps:
            - checkout
            - setup_remote_docker
            - run: sudo composer self-update
            - restore_cache:
                keys:
                    - composer-v1-{{ checksum "composer.json" }}
                    - composer-v1-
            - run: rm -rf var/cache/*
            - run: cp .env.dist .env
            - run: cp .env.behat.dist .env.behat
            - run: cp phpunit.xml.dist phpunit.xml
            - run: mkdir -p ${HOME}/project/config/credentials/google/bucket
            - run: mkdir -p ${HOME}/project/config/credentials/google/vision
            - run: echo $GCP_BUCKET_CREDENTIALS | base64 --decode --ignore-garbage > ${HOME}/project/config/credentials/google/bucket/credentials.json
            - run: echo $GCP_VISION_CREDENTIALS | base64 --decode --ignore-garbage > ${HOME}/project/config/credentials/google/vision/credentials.json
            - run: composer install -n --optimize-autoloader --classmap-authoritative
            - run: composer dump-autoload --optimize --classmap-authoritative
            - save_cache:
                key: composer-v1-{{ checksum "composer.json" }}
                paths:
                    - vendor
            - run: ./bin/console d:d:c --env=test
            - run: ./bin/console d:s:c --env=test
            - run: vendor/bin/phpunit -v
            - run: rm -rf var/data.db
    behat_core:
        docker:
            - image: circleci/php:7.2.2-apache-node-browsers
            - image: redis
        steps:
            - checkout
            - setup_remote_docker
            - run: sudo composer self-update
            - restore_cache:
                keys:
                    - composer-v1-{{ checksum "composer.json" }}
                    - composer-v1-
            - run: composer install -n --optimize-autoloader --classmap-authoritative
            - run: composer dump-autoload --optimize --classmap-authoritative
            - save_cache:
                key: composer-v1-{{ checksum "composer.json" }}
                paths:
                    - vendor
            - run: cp .env.dist .env
            - run: cp .env.behat.dist .env.behat
            - run: mkdir -p ${HOME}/project/config/credentials/google/bucket
            - run: mkdir -p ${HOME}/project/config/credentials/google/vision
            - run: echo $GCP_BUCKET_CREDENTIALS | base64 --decode --ignore-garbage > ${HOME}/project/config/credentials/google/bucket/credentials.json
            - run: echo $GCP_VISION_CREDENTIALS | base64 --decode --ignore-garbage > ${HOME}/project/config/credentials/google/vision/credentials.json
            - run: ./bin/console d:d:c --env=test
            - run: ./bin/console d:s:c --env=test
            - run: vendor/bin/behat --profile default
            - run: rm -rf var/data.db
    gcloud_kubernetes_check:
        docker:
            - image: google/cloud-sdk
        steps:
            - checkout
            - run: echo $GCP_SERVICE_CREDENTIALS > /tmp/gcp_key.json
            - run: gcloud config set project $GCP_PROJECT_NAME
            - run: gcloud auth activate-service-account --key-file /tmp/gcp_key.json
            - run: gcloud container clusters get-credentials $GCK_CLUSTER_NAME --zone $GCK_CLUSTER_ZONE --project $GCP_PROJECT_NAME
            - run: kubectl get nodes

workflows:
    version: 2
    unit_and_spec:
        jobs:
            - phpunit
    functional:
        jobs:
            - behat_core
    staging:
        jobs:
            - gcloud_kubernetes_check:
                requires:
                    - behat_core
