version: 2
jobs:
    phpspec:
        docker:
            - image: circleci/php:7.1-fpm
        steps:
            - checkout
            - run: sudo composer self-update
            - restore_cache:
                keys:
                    - composer-v1-{{ checksum "composer.json" }}
                    - composer-v1-
            - run: composer install -n --optimize-autoloader --classmap-authoritative
            - run: composer dump-autoload --optimize --classmap-authoritative
            - save_cache:
                key: composer-v1-{{ checksum "composer.json" }}
                paths:
                    - vendor
            - run: cp .env.dist .env
            - run: vendor/bin/phpspec run
    phpunit:
        docker:
            - image: circleci/php:7.1-fpm
            - image: redis
        steps:
            - checkout
            - run: sudo composer self-update
            - restore_cache:
                keys:
                    - composer-v1-{{ checksum "composer.json" }}
                    - composer-v1-
            - run: rm -rf var/cache/*
            - run: cp .env.dist .env
            - run: cp .env.behat.dist .env.behat
            - run: composer install -n --optimize-autoloader --classmap-authoritative
            - run: composer dump-autoload --optimize --classmap-authoritative
            - save_cache:
                key: composer-v1-{{ checksum "composer.json" }}
                paths:
                    - vendor
            - run: ./bin/console d:d:c --env=test
            - run: ./bin/console d:s:c --env=test
            - run: vendor/bin/phpunit -v
            - run: rm -rf var/data.db
    behat_core:
        docker:
            - image: circleci/php:7.1-node-browsers
            - image: redis
        steps:
            - checkout
            - run: sudo composer self-update
            - restore_cache:
                keys:
                    - composer-v1-{{ checksum "composer.json" }}
                    - composer-v1-
            - run: composer install -n --optimize-autoloader --classmap-authoritative
            - run: composer dump-autoload --optimize --classmap-authoritative
            - save_cache:
                key: composer-v1-{{ checksum "composer.json" }}
                paths:
                    - vendor
            - run: cp .env.dist .env
            - run: cp .env.behat.dist .env.behat
            - run: mkdir -p $CIRCLE_WORKING_DIRECTORY/config/credentials/google/bucket
            - run: rm -rf $CIRCLE_WORKING_DIRECTORY/config/credentials/google/bucket/*.json
            - run: echo $GCP_SERVICE_CREDENTIALS > $CIRCLE_WORKING_DIRECTORY/config/credentials/google/bucket/credentials.json
            - run: ls -l $CIRCLE_WORKING_DIRECTORY/config/credentials/google/bucket
            - run: ./bin/console d:d:c --env=test
            - run: ./bin/console d:s:c --env=test
            - run: vendor/bin/behat --profile default
            - run: rm -rf var/data.db
    gcloud_kubernetes_check:
        docker:
            - image: google/cloud-sdk
        steps:
            - checkout
            - run: echo $GCP_SERVICE_CREDENTIALS > /tmp/gcp_key.json
            - run: gcloud config set project $GCP_PROJECT_NAME
            - run: gcloud auth activate-service-account --key-file /tmp/gcp_key.json
            - run: gcloud container clusters get-credentials $GCK_CLUSTER_NAME --zone $GCK_CLUSTER_ZONE --project $GCP_PROJECT_NAME
            - run: kubectl get nodes

workflows:
    version: 2
    unit_and_spec:
        jobs:
            - phpspec
            - phpunit
    functional:
        jobs:
            - behat_core
    staging:
        jobs:
            - gcloud_kubernetes_check:
                requires:
                    - behat_core
