App\Domain\UseCase\UserRegistration\DTO\ImageRegistrationDTO:
    properties:
        file:
            - Image:
                mimeTypes:
                    - image/jpeg
                    - image/png
                mimeTypesMessage: "image.type_forbidden"
                groups: ['imageUpload']

