App\Domain\Models\User:
     constraints:
         - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
             fields:
                 - username
                 - email
             message: "credentials.already_exist"
             groups: ['registration']
