App\Interactor\UserInteractor:
    properties:
        username:
            - NotBlank:
                message: "This entry must be filled !"
                groups: ['registration']
            - Length:
                min: 3
                minMessage: "This value is too short"
                max: 25
                maxMessage: "This value is too long"
                groups: ['registration']
        email:
            - NotBlank:
                message: "This entry must be filled !"
                groups: ['registration']
            - Length:
                min: 10
                minMessage: "This value is too short"
                max: 50
                maxMessage: "This value is too long"
                groups: ['registration']
            - Email:
                message: "The value `{{ value }}` must be a valid email !"
        plainPassword:
            - NotBlank:
                message: "This entry must be filled !"
                groups: ['registration']
            - Length:
                min: 5
                minMessage: "This value is too short"
                max: 25
                maxMessage: "This value is too long"
                groups: ['registration']
