App\Domain\UseCase\UserResetPassword\DTO\UserNewPasswordDTO:
    properties:
        password:
            - NotBlank:
                message: "validation.filled"
                groups: ['resetPassword']
            - Length:
                min: 5
                minMessage: "validation.length_short"
                max: 25
                maxMessage: "validation.length_long"
                groups: ['resetPassword']
