App\Domain\UseCase\UserResetPassword\DTO\UserResetPasswordDTO:
    constraints:
        - App\Application\Validator\UserExist:
              exist: false
    properties:
         username:
             - NotBlank:
                 message: "validation.filled"
             - Length:
                 min: 3
                 minMessage: "validation.length_short"
                 max: 25
                 maxMessage: "validation.length_long"
         email:
             - NotBlank:
                 message: "validation.filled"
             - Length:
                 min: 10
                 minMessage: "validation.length_short"
                 max: 50
                 maxMessage: "validation.length_long"
             - Email:
                 message: "email.wrong_format"
