App\Domain\DTO\UserResetPasswordDTO:
    properties:
         username:
             - NotBlank:
                 message: "validation.filled"
                 groups: ['resetPassword']
            - Length:
                min: 3
                minMessage: "validation.length_short"
                max: 25
                maxMessage: "validation.length_long"
                groups: ['resetPassword']
        email:
            - NotBlank:
                message: "validation.filled"
                groups: ['resetPassword']
            - Length:
                min: 10
                minMessage: "validation.length_short"
                max: 50
                maxMessage: "validation.length_long"
                groups: ['resetPassword']
            - Email:
                message: "The value `{{ value }}` must be a valid email !"
