Image:
    type: object
    config:
        description: "An image who can be linked to an user"
        fields:
            id:
                type: "Int"
                description: "The identifier of the Interfaces"
            creationDate:
                type: "String"
                description: "The creation date of the Interfaces"
            modificationDate:
                type: "String"
                description: "The modification date of the Interfaces"
            alt:
                type: "String"
                description: "The replacement text of the Interfaces"
            url:
                type: "String"
                description: "The relative path of the Interfaces"
            user:
                type: "User"
                description: "The user who's the proprietary of the Interfaces"
