Mutation:
    type: object
    config:
        description: ""
        fields:
        # User management
           register_user:
               type: "User"
               args:
                   username:
                       type: "String!"
                   password:
                       type: "String!"
                   email:
                       type: "String!"
               resolve: "@graphql.user_mutator=('register', [args])"
           forgot_password:
               type: "User"
               args:
                   email:
                       type: "String!"
                   newPassword:
                       type: "String!"
               resolve: "@graphql.user_mutator=('forgot_password', [args])"
           login_user:
               type: "User"
               args:
                   username:
                       type: "String!"
                   password:
                       type: "String!"
               resolve: "@graphql.user_mutator=('login_user', [args])"
           drop_user:
               type: "User"
               args:
                   username:
                       type: "String!"
                   email:
                       type: "String!"
               resolve: "@graphql.user_mutator=('drop_user', [args])"

        # Interfaces management
           add_image:
               type: "Interfaces"
               args:
                   user:
                       type: "Int!"
                   alt:
                       type: "String"
                   url:
                       type: "String"
               resolve: "@graphql.image_mutator=('image_creation', [args])"
           create_stock:
               type: "Stock"
               args:
                   user:
                       type: "Int!"
                   alt:
                       type: "String"
                   url:
                       type: "String"
               resolve: "@graphql.image_mutator=('image_creation', [args])"
           add_products:
               type: "Products"
               args:
                   stock:
                       type: "Int!"
                   alt:
                       type: "String"
                   url:
                       type: "String"
               resolve: "@graphql.image_mutator=('image_creation', [args])"
