Query:
    type: object
    config:
        description:
        fields:
            user:
                type: "[User]"
                description: "An user registered into the application"
                args:
                    id:
                        type: "Int"
                        description: "The id of the User, if omitted, return all the users."
                resolve: "@=service('graphql.user_resolver').getUser(args)"
            image:
                type: "[Image]"
                description: "An image linked to an user"
                args:
                    id:
                        type: "Int"
                        description: "The id of the Image, if omitted, the whole images are returned."
                resolve: "@=service('graphql.image_resolver').getImage(args)"
            stock:
                type: "[Stock]"
                description: "A stock saved and linked to an user"
                args:
                    id:
                        type: "Int"
                        description: "The id of the Stock"
                resolve: "@=service('graphql.stock_resolver').getStock(args)"
            products:
                type: "[Products]"
                description: "A product saved and linked to a stock, if omitted, return all the stocks"
                args:
                    id:
                        type: "Int"
                        description: "The id of the product, if omitted, return all the products."
                resolve: "@=service('graphql.products_resolver').getProduct(args)"
