User:
    type: object
    config:
        description: "An user who's registered in the application."
        fields:
            id:
                type: "Int"
                description: "The identifier of the user"
            firstname:
                type: "String"
                description: "The firstname of the user"
            lastname:
                type: "String"
                description: "The lastname of the user"
            username:
                type: "String"
                description: "The username of the user"
            email:
                type: "String"
                description: "The email of the user"
            roles:
                type: "String"
                description: "The roles of the user"
            creationDate:
                type: "String"
                description: "The creation date of the user"
            validationDate:
                type: "String"
                description: "The validation date of the user"
            validated:
                type: "Boolean"
                description: "If the user is validated"
            active:
                type: "Boolean"
                description: "If the user is active"
            image:
                type: "Image"
                description: "The image of the user"
            stocks:
                type: "Stock"
                description: "The stocks of the user"
