controllers:
    resource: ../src/UI/Action/
    type: annotation
    prefix: /{_locale}
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%accepted_locales%'

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: 'index'
        permanent: true

logout:
    path: /logout
