root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: 'index'
        permanent: true

index:
    path: /{_locale}/
    methods: ["GET"]
    defaults:
        _controller: App\Action\Core\HomeAction
    requirements:
        _locale: 'fr|en'

web_register:
    path:    /{_locale}/register
    methods: ['GET', 'POST']
    defaults:
        _controller: App\Action\Security\RegisterAction
        _locale: '%locale%'
    requirements:
        _locale: 'fr|en'
