controllers:
    resource: ../src/UI/Action/
    type: annotation
    prefix: /{_locale}
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%accepted_locales%'

api_login:
    path: /rest/login
    defaults:
        _controller: App\UI\Action\API\LoginAction

root:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: 'index'
        permanent: true

logout:
    path: /logout
