index:
    path:    /{_locale}

web_register:
    path:    /{_locale}/register
    methods: ['GET', 'POST']
    defaults:
        _controller: 'App\Action\Security\RegisterAction'
        _locale: '%locale%'
    requirements:
        _locale: '%locale%'
