controllers:
    resource: ../src/UI/Action/
    type: annotation

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: 'index'
        permanent: true

logout:
    path: /logout
