parameters:
    locale: 'fr'
    accepted_locales: '%env(ACCEPTED_LOCALES)%'
    accepted_channels: '%env(ACCEPTED_CHANNELS)%'
    kernel.docker_dir: "%kernel.project_dir%/docker/config"
    kernel.images_dir: "%kernel.project_dir%/public/images/profiles"

    ## Cloud Storage
    cloud.credentials_filename: "credentials.json"
    cloud.credentials_folder: '%kernel.project_dir%/config/credentials/google'
    cloud.storage.public_url: "%env(GOOGLE_STORAGE_URL)%%env(GOOGLE_BUCKET_NAME)%/"
    cloud.storage.bucket_name: "%env(GOOGLE_BUCKET_NAME)%"

    ## Cloud Vision
    forbidden_labels:
        - 'drugs'
        - 'gun'
        - 'sex'
        - 'money'

    ## Redis
    redis.dsn: '%env(REDIS_URL)%'
    redis.namespace_dev: "dev"
    redis.namespace_prod: "prod"

    ## SendGrid
    email.sender_address: "%env(SENDER_EMAIL_ADDRESS)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $acceptedChannels: "%accepted_channels%"
            $acceptedLocales: "%accepted_locales%"
            $defaultLocale: "%locale%"
            $filePath: "%kernel.images_dir%"
            $emailSender: "%email.sender_address%"

            ## Redis
            $redisDSN: '%redis.dsn%'
            $namespace: '%env(APP_ENV)%'

            ## Cloud Storage
            $bucketName: "%cloud.storage.bucket_name%"
            $googleStoragePublicUrl: "%cloud.storage.public_url%"

            ## Cloud Translation
            $credentialsFilename: "%cloud.credentials_filename%"
            $credentialsFolder: "%cloud.credentials_folder%"
            $translationsFolder: "%translator.default_path%"

            # Cloud Vision
            $forbiddenLabels: '%forbidden_labels%'

    App\:
        resource: '../src/*'
        exclude: '../src/{Domain/Models,Domain/UseCase,Application/Migrations,Repository,Kernel.php}'

    App\UI\Action\:
        resource: '../src/UI/Action'
        tags: ['controller.service_arguments']

    App\UI\Form\Extension\StockTagsTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: App\UI\Form\Type\StockTagsType }

    App\UI\Form\Extension\CloudTranslationTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }


    App\Application\DataCollector\RequestHandlerDataCollector:
        public: false
        tags:
            - { name: data_collector, template: "application/data_collector/request_handler_collector.html.twig", id: 'requestHandler' }
