parameters:
    kernel.test_dir: '%kernel.project_dir%/tests'
    cloud.credentials_folder: '%kernel.project_dir%/tests/_credentials'
    translator.test_path: '%kernel.test_dir%/_translations'

services:
    _defaults:
        public: true
        bind:
            # CloudTranslation
            $translationsFolder: "%translator.test_path%"
