parameters:
    cloud.credentials_folder: '%kernel.project_dir%/tests/_credentials'

services:
    _defaults:
        public: true
        bind:
            ## Redis
            $redisDSN: '%redis.test_dsn%'
            $namespace: '%env(APP_ENV)%'
