parameters:
    locale: 'fr'
    accepted_locales: 'fr|en'
    kernel.docker_dir: "%kernel.project_dir%/docker/config"
    kernel.images_dir: "%kernel.project_dir%/public/images/profiles"
    cloud.storage_credentials: "%kernel.project_dir%/config/credentials/google/bucket"
    cloud.vision_credentials: "%kernel.project_dir%/config/credentials/google/vision"
    cloud.storage.bucket_name: "%env(GOOGLE_BUCKET_NAME)%"
    cloud.storage.public_url: "%env(GOOGLE_STORAGE_URL)%%env(GOOGLE_BUCKET_NAME)%/"
    email.sender_address: "%env(SENDER_EMAIL_ADDRESS)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $defaultLocale: "%locale%"
            $bucketCredentialsFolder: "%cloud.storage_credentials%"
            $visionCredentialsFolder: "%cloud.vision_credentials%"
            $filePath: "%kernel.images_dir%"
            $bucketName: "%cloud.storage.bucket_name%"
            $googleStoragePublicUrl: "%cloud.storage.public_url%"
            $emailSender: "%email.sender_address%"

    App\:
        resource: '../src/*'
        exclude: '../src/{Domain/Models,Domain/UseCase,Migrations,Repository,Kernel.php}'

    App\UI\Action\:
        resource: '../src/UI/Action'
        tags: ['controller.service_arguments']
#
#    graphql.image_resolver:
#        class: App\Resolvers\ImageResolver
#        arguments:
#            - '@doctrine.orm.entity_manager'
#        tags:
#            - { name: overblog_graphql.resolver, alias: 'image_resolver', method: getImage }
#
#    graphql.user_resolver:
#        class: App\Resolvers\UserResolver
#        arguments:
#            - '@doctrine.orm.entity_manager'
#        tags:
#            - { name: overblog_graphql.resolver, alias: 'user_resolver', method: getUser }
#
#    graphql.stock_resolver:
#        class: App\Resolvers\StockResolver
#        arguments:
#            - '@doctrine.orm.entity_manager'
#        tags:
#            - { name: overblog_graphql.resolver, alias: 'stock_resolver', method: getStock }
#
#    graphql.products_resolver:
#        class: App\Resolvers\ProductsResolver
#        arguments:
#            - '@doctrine.orm.entity_manager'
#        tags:
#            - { name: overblog_graphql.resolver, alias: 'products_resolver', method: getProduct }
#
#    graphql.user_mutator:
#        class: App\Mutators\UserMutator
#        tags:
#            - { name: overblog_graphql.mutation, method: register }
#            - { name: overblog_graphql.mutation, method: login }
#            - { name: overblog_graphql.mutation, method: forgotPassword }
#            - { name: overblog_graphql.mutation, method: dropUser }
#
#    graphql.image_mutator:
#        class: App\Mutators\ImageMutator
#        tags:
#            - { name: overblog_graphql.mutation, alias: 'image_creation', method: createImage }
#
#    graphql.stock_mutator:
#        class: App\Mutators\StockMutator
#        tags:
#            - { name: overblog_graphql.mutation, alias: 'stock_creation', method: createStock }
