parameters:
    locale: 'fr'
    accepted_locales: 'fr|en'
    accepted_channels: 'messages|validators|session'
    kernel.docker_dir: "%kernel.project_dir%/docker/config"
    kernel.images_dir: "%kernel.project_dir%/public/images/profiles"

    ## Cloud Storage
    cloud.storage.bucket_name: "%env(GOOGLE_BUCKET_NAME)%"
    cloud.storage_credentials: "%kernel.project_dir%/config/credentials/google/bucket"
    cloud.storage_credentials.filename: "credentials.json"
    cloud.storage.public_url: "%env(GOOGLE_STORAGE_URL)%%env(GOOGLE_BUCKET_NAME)%/"

    ## Cloud Translation
    cloud.translation_credentials: "%kernel.project_dir%/config/credentials/google/translation"
    cloud.translation_credentials.filename: "credentials.json"

    ## Cloud Vision
    cloud.vision_credentials: "%kernel.project_dir%/config/credentials/google/vision"
    cloud.vision_credentials.filename: "credentials.json"

    ## Redis
    redis.dsn: '%env(REDIS_URL)%'
    redis.test_dsn: '%env(REDIS_TEST_URL)%'
    redis.namespace_dev: "dev"
    redis.namespace_prod: "prod"
    redis.namespace_test: "test"

    ## SendGrid
    email.sender_address: "%env(SENDER_EMAIL_ADDRESS)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $acceptedChannels: "%accepted_channels%"
            $acceptedLocales: "%accepted_locales%"
            $defaultLocale: "%locale%"
            $filePath: "%kernel.images_dir%"
            $emailSender: "%email.sender_address%"

            ## Redis
            $redisDSN: '%redis.dsn%'
            $namespace: '%env(APP_ENV)%'

            ## Cloud Storage
            $storageCredentialsFileName: "%cloud.storage_credentials.filename%"
            $storageCredentialsFolder: "%cloud.storage_credentials%"
            $bucketName: "%cloud.storage.bucket_name%"
            $googleStoragePublicUrl: "%cloud.storage.public_url%"

            ## Cloud Translation
            $translationCredentialsFileName: "%cloud.translation_credentials.filename%"
            $translationCredentialsFolder: "%cloud.translation_credentials%"
            $translationsFolder: "%translator.default_path%"

            ## Cloud Vision
            $visionCredentialsFileName: "%cloud.vision_credentials.filename%"
            $visionCredentialsFolder: "%cloud.vision_credentials%"

    App\:
        resource: '../src/*'
        exclude: '../src/{Domain/Models,Domain/UseCase,Infra/GCPMigrations,Repository,Kernel.php}'

    App\UI\Action\:
        resource: '../src/UI/Action'
        tags: ['controller.service_arguments']
