parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Repository}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    graphql.image_resolver:
        class: App\Resolvers\ImageResolver
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: overblog_graphql.resolver, alias: 'image_id', method: 'getImage' }
