App\Models\Stock:
    type: entity
    repositoryClass: App\Repository\StockRepository
    table: marketReminder_stock
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        creationDate:
            type: datetime
            nullable: false
        modificationDate:
            type: datetime
            nullable: true
        status:
            type: string
            length: 20
            nullable: false

    manyToOne:
        user:
            targetEntity: App\Models\User
            inversedBy: stocks
            joinColumn:
                name: user_id
                referencedColumnName: id

    oneToMany:
        products:
            targetEntity: App\Models\Products
            mappedBy: stock