App\Interactor\UserInteractor:
    type: entity
    repositoryClass: App\Repository\UserRepository
    table: marketReminder_user
    id:
         id:
             type: integer
             generator:
                 strategy: AUTO
    fields:
         username:
             type: string
             length: 50
             nullable: false
         email:
             type: string
             length: 100
             nullable: false
         password:
             type: string
             length: 60
             nullable: false
         roles:
             type: array
             nullable: false
         creationDate:
             type: datetime
             nullable: false
         validationDate:
             type: datetime
             nullable: true
         validated:
             type: boolean
             nullable: false
         validationToken:
             type: string
             length: 35
             nullable: true
             unique: true
         active:
             type: boolean
             nullable: true
         currentState:
             type: string
             length: 10
             nullable: false
             unique: false

    oneToOne:
        profileImage:
            targetEntity: App\Interactor\ImageInteractor
            inversedBy: user
            joinColumn:
                name: image_id
                referencedColumnName: id
