App\Models\User:
    type: entity
    table: marketReminder_user
    id:
         id:
             type: integer
             generator: { strategy: AUTO }
    fields:
         firstname:
             type: string
             length: 70
             nullable: true
         lastname:
             type: string
             length: 70
             nullable: true
         username:
             type: string
             length: 50
             nullable: false
         email:
             type: string
             length: 100
             nullable: false
         password:
             type: string
             length: 60
             nullable: false
         roles:
             type: array
             nullable: false
         creationDate:
             type: datetime
             nullable: false
         validationDate:
             type: datetime
             nullable: true
         validated:
             type: boolean
             nullable: false
         active:
             type: boolean
             nullable: true
         apiToken:
             type: string
             length: 255
             nullable: true

    oneToOne:
        image:
            targetEntity: App\Models\Image
            inversedBy: user
            joinColumn:
                name: image_id
                referencedColumnName: id

    oneToMany:
        stocks:
            targetEntity: App\Models\Stock
            mappedBy: user
